[package]
name = "ra-proc-macro-rebuild-issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yare = "3.0.0"
